[build]
  command = "npm install && npm run build"
  publish = "../dist/arc-raider-info/browser"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
   from = "/api/*"
   to = "https://metaforge.app/api/:splat"
   status = 200
   force = true

